docusaurus.config.ts
package.json
pnpm-lock.yaml
src/components/HomePageFAQ/index.tsx
src/components/HomePageFAQ/styles.module.css
src/css/custom.css
src/pages/index.tsx
tailwind.config.js

https://github.com/ZenUml/docs/assets/125171539/1800897e-6fc3-440a-a096-4f34dde7fa45

feat: add `faq` section

---

docusaurus.config.ts

feat:navbar hidenOnScroll

---

docs/tutorials/elements-in-sequence-diagrams.md
docs/tutorials/what-is-sequence-diagrams.md

New tutorials post
https://docs.docs-68d.pages.dev/docs/tutorials/elements-in-sequence-diagrams

docs:elements-in-seq-diagrams

---

src/pages/best-plantuml-alternative.md

尝试 Hack 流量……先缝合了一篇，打算挂两个礼拜看看收录还有流量情况。
https://content.docs-68d.pages.dev/best-plantuml-alternative/

docs:add plantuml alternative page

---

src/pages/best-lucidchart-alternative-for-sequence-diagrams.md
src/pages/best-mermaid-alternative-for-sequence-diagrams.md
src/pages/best-plantuml-alternative.md

docs:add 2 more posts and updated meta data

---

docs/examples/sequence-diagram-example-credit-card-transaction-process.md
docs/examples/sequence-diagram-example-dns-resolve-process.md

1. DNS process
2. Payment process

Add 2 more examples to Docs

---

blog/2024/2024-05-22-mastering-if-else-logic-with-sequence-diagrams.md

---
title: 'Mastering If-Else Logic with Sequence Diagrams'
description: 'Discover how to effectively represent and communicate if-else logic in your software applications using sequence diagrams. Learn the benefits of this approach for improved communication, understanding, debugging, and documentation.'
tags:
- If-else logic
- Software development
- UML
- Control flow
- Decision-making
- Visualization
- Debugging
- Documentation
---

New Blog: title: 'Mastering If-Else Logic with Sequence Diagrams'

---

blog/2024/2024-05-22-mastering-if-else-logic-with-sequence-diagrams.md
blog/2024/2024-05-24-why-zenUML-is-the-best-choice-for-diagram-plugin-in-confluence.md

description: "Discover how ZenUML, the powerful Confluence plugin, revolutionizes diagram maintenance with its diagram as code approach. Leverage seamless integration, Mermaid and Draw.io capabilities, and cost-effective pricing to transform your team's visual documentation workflow within Confluence."
tags:
- ZenUML
- Confluence plugin
- Diagram as code
- Mermaid
- Draw.io
- Collaboration
- Documentation
- Cost-effective

New Post | title: 'Why ZenUML is the Best Choice for Diagram Plugin in Confluence'

---

blog/2024/2024-05-25-business-process-modeling-reengineering-product-return-refund-process.md

---
title: 'Streamlining the Product Return and Refund Process: A Business Process Modeling and Reengineering Approach'
description: 'Discover how businesses can optimize their product return and refund process through business process modeling and reengineering, leading to enhanced customer experience, reduced operational costs, and improved efficiency.'
tags:
- Business process modeling
- Business process reengineering
- Product return
- Refund process
- Customer experience
- Operational efficiency
- Inventory management
---

New Blog: 'Streamlining the Product Return and Refund Process: A Business Process Modeling and Reengineering Approach'

---

blog/2024/2024-05-26-the-impact-of-sequence-diagrams-on-system-scalability.md

---
title: 'Unveiling the Secrets of Scalable Software: The Transformative Power of Sequence Diagrams'
description: 'Discover how sequence diagrams can transform your software system's scalability. Explore the role of sequence diagrams in communication, complexity management, performance optimization, and scalability testing. Learn how to unlock the power of sequence diagrams for building high-performing, scalable systems.'
tags:
- System Scalability
- Software Architecture
- Performance Optimization
- Complexity Management
- Scalability Testing
---

New Blog: Unveiling the Secrets of Scalable Software: The Transformative Power of Sequence Diagrams

---

blog/2024/2024-05-28-streamlining-policy-underwriting-optimizing-business-processes-with-sequence-diagrams.md

---
title: 'Streamlining Policy Underwriting: Optimizing Business Processes with Sequence Diagrams'
description: 'Discover how to streamline your policy underwriting process and enhance efficiency with the power of business process modeling and sequence diagrams. Unlock cost savings, improve customer experience, and drive sustainable growth for your insurance organization.'
tags:
- Policy Underwriting
- Insurance Industry
- Efficiency
- Customer Experience
---

New Blog: 'Streamlining Policy Underwriting: Optimizing Business Processes with Sequence Diagrams'

---

blog/2024/2024-05-29-optimizing-sla-management-through-business-process-modeling.md

---
title: 'Optimizing Service Level Agreement Management Through Business Process Modeling'
description: 'Discover how business process modeling can help organizations optimize their Service Level Agreement (SLA) management practices, improve visibility, streamline workflows, and enhance collaboration for better customer satisfaction and financial performance.'
tags:
- Service Level Agreement
- SLA Onboarding
- SLA Breach Management
- SLA Reporting and Analytics
- Workflow Automation
- Collaboration and Communication
---

New Blog: 'Optimizing Service Level Agreement Management Through Business Process Modeling'

---

blog/2024/2024-05-31-healthcare-appointment-scheduling-business-process-modeling.md
docusaurus.config.ts

---
title: 'Streamlining Healthcare Appointment Scheduling with Business Process Modeling'
description: 'Discover how business process modeling can revolutionize healthcare appointment scheduling, leading to increased efficiency, enhanced patient experience, and data-driven decision-making. Explore practical examples and visual sequence diagrams to optimize your healthcare organization's scheduling workflows.'
tags:
- Business process modeling
- Healthcare appointment scheduling
- Workflow optimization
- Patient experience
- Data-driven decision making
- Sequence diagram
---

New Blog: 'Streamlining Healthcare Appointment Scheduling with Business Process Modeling'

---

blog/2024/2024-06-01-revolutionizing-fraud-detection-business-process-modeling.md

---
title: 'Revolutionizing Fraud Detection: A Business Process Modeling Approach'
description: 'Discover how business process modeling can revolutionize your fraud detection strategies. Streamline workflows, identify vulnerabilities, and enhance analytics to safeguard your organization from the growing threat of fraud.'
tags:
- Fraud Detection
- Workflow Optimization
- Vulnerability Analysis
- Fraud Analytics
---

New Blog: 'Revolutionizing Fraud Detection: A Business Process Modeling Approach'

---

blog/2024/2024-06-02-streamlining-change-management-leveraging-sequence-diagrams.md

---
title: 'Revolutionize Your Change Management with ZenUML Sequence Diagrams'
description: 'Discover how to streamline your change management process and enhance organizational agility by leveraging the power of ZenUML sequence diagrams. Explore practical examples and insights to improve communication, collaboration, and the successful implementation of changes within your business.'
tags:
- Change Management
- Organizational Agility
- Process Visualization
---

New Blog: 'Revolutionize Your Change Management with ZenUML Sequence Diagrams'

---

blog/2024/2024-06-04-sequence-diagrams-machine-learning-new-perspective.md

---
title: 'Sequence Diagrams and Machine Learning: A New Perspective'
description: 'Discover the powerful intersection of sequence diagrams and machine learning, and how they can revolutionize software development, enhance system analysis, and drive innovation across industries. Explore the benefits of integrating these two technologies and learn about the latest advancements in automated diagram generation, anomaly detection, and predictive modeling.'
tags:
- Machine learning
- Software engineering
- System analysis
- Automated diagram generation
- Anomaly detection
- Predictive modeling
- Optimization
- Workflow integration
---

New Blog: 'Sequence Diagrams and Machine Learning: A New Perspective'

---

blog/2024/2024-06-05-effective-business-process-modeling-for-responding-to-cyber-security-events.md

---
title: 'Effective Business Process Modeling for Responding to Cyber Security Events'
description: 'Discover how effective business process modeling can enhance your organizations cyber security event response, minimizing the impact of cyber threats and boosting overall cyber resilience. Explore key components, integration strategies, and real-world examples to optimize your incident response capabilities.'
tags:
- Cyber security event response
- Business process modeling
- Incident response plan
- Cyber resilience
- Cyber threat management
- Regulatory compliance
- Vendor and third-party management
---

New Blog: 'Effective Business Process Modeling for Responding to Cyber Security Events'

---

blog/2024/2024-06-06-confluence-diagramming-plugin-with-drawio-zenuml.md

---
title: 'Best Draw.IO for Confluence Solution: ZenUML All-In-One'
description: 'Unlock the power of diagramming in Confluence with the ZenUML plugin. Discover how DrawIO integration enhances collaboration, visualization, and cost-effectiveness for your team. Boost productivity and communication with advanced sequence diagram capabilities.'
tags:
- Confluence
- ZenUML
- DrawIO
- Diagrams
- Collaboration
- Visualization
- Cost-effective
---

New Blog for Draw.IO Keyword: 'Best Draw.IO for Confluence Solution: ZenUML All-In-One'

---

blog/2024/2024-06-08-mermaid-for-confluence-with-zenuml.md

---
title: 'Best Mermaid for Confluence Solution: ZenUML All-In-One'
description: 'Enhance your Confluence pages with ZenUML, supporting Mermaid for versatile, cost-effective, and high-quality diagramming solutions, ideal for collaborative environments.'
tags:
- ZenUML for Confluence
- Mermaid for Confluence
- Confluence diagramming tool
- Cost-effective diagramming
- Collaborative workflow
- Interactive diagrams
- Confluence plugin
---

New Blog for 'Best Mermaid for Confluence Solution: ZenUML All-In-One'

---

blog/2024/2024-06-08-mermaid-for-confluence-with-zenuml.md
blog/2024/2024-06-10-streamlining-food-delivery-order-processing.md

---
title: 'Elevate Your Food Delivery Game: Mastering Order Processing Workflows for Maximum Efficiency'
description: 'Optimize your food delivery order processing workflow with proven strategies like leveraging digital technologies, streamlining order placement, enhancing preparation efficiency, and implementing feedback loops. Learn how to create a seamless and efficient order processing system that delivers exceptional customer experiences.'
tags:
- Food Delivery
- Order Processing
- Workflow Optimization
- Digital Technologies
- Customer Experience
- Process Reenginerring
---

New Blog: 'Elevate Your Food Delivery Game: Mastering Order Processing Workflows for Maximum Efficiency'

---

blog/2024/2024-06-11-streamlining-budget-approval-with-sequence-diagrams.md

---
title: 'Business Analysis: Budget Approval Process with Sequence Diagrams'
description: 'Discover how sequence diagrams can streamline your budget approval process, enhance transparency, and support strategic decision-making. Explore practical examples and the role of sequence diagrams in business process modeling and analysis.'
tags:
- Business Process
- Budget Approval
- Resource Management
- Decision-Making
---

New Blog: 'Business Analysis: Budget Approval Process with Sequence Diagrams'

---

blog/2024/2024-06-12-best-business-process-analysis-tool-is-sequence-diagram.md

---
title: 'Best Business Process Analysis Tool: Sequence Diagram'
description: 'Discover why the sequence diagram is the best tool for business process analysis, learn how to leverage it for optimization, and explore practical examples to enhance your operations.'
tags:
- Business Process
- Business Analysis Tool
- Process Improvement
- Workflow Efficiency
---

New Blog: 'Best Business Process Analysis Tool: Sequence Diagram'

---

blog/2024/2024-06-14-business-process-analysis-payroll-processing-sequence-diagram.md

---
title: 'Business Process Analysis For Payroll Processing Using Sequence Diagram'
description: 'Discover how business process analysis and sequence diagrams can revolutionize your payroll processing workflow. Gain insights into data validation, process mapping, and optimization strategies to enhance efficiency and accuracy.'
tags:
- Business Process
- Payroll Processing
- Data Validation
- Process Mapping
---

New Blog: 'Business Process Analysis For Payroll Processing Using Sequence Diagram'

---

blog/2024/2024-06-17-business-process-analysis-feature-request-gathering-prioritization.md

---
title: 'Mastering Business Process Analysis: Streamlining Feature Request Gathering and Prioritization'
description: 'Discover how to streamline your feature request gathering and prioritization process using business process analysis and sequence diagrams. Learn to identify stakeholders, map current workflows, and optimize for maximum efficiency and value delivery.'
tags:
- Business Process Analysis
- Feature Request Gathering
- Feature Request Prioritization
- Product Management
- Backlog Management
- Stakeholder Engagement
- Workflow Optimization
---

New Blog: 'Mastering Business Process Analysis: Streamlining Feature Request Gathering and Prioritization'

---

blog/2024/2024-07-01-power-of-sequence-diagrams-in-business-process-analysis.md

---
title: 'The Unparalleled Power of Sequence Diagrams in Business Process Analysis'
description: 'Discover how sequence diagrams can revolutionize your business process analysis, unlock new levels of efficiency, and drive organizational success. Explore the practical applications and best practices for leveraging this powerful visualization tool.'
tags:
- Business Process Analysis
- Process Improvement
- Workflow Visualization
- Communication and Collaboration
- Process Simulation and Validation
---

New Blog: 'The Unparalleled Power of Sequence Diagrams in Business Process Analysis'

---

blog/2024/2024-07-20-mastering-domain-driven-design-with-sequence-diagrams.md

---
title: 'Unlocking the Power of Sequence Diagrams in Domain-Driven Design'
description: 'Discover the power of Sequence Diagrams in Domain-Driven Design and Business Analysis. Learn how to leverage this visual tool to enhance collaboration, identify pain points, validate requirements, and optimize business processes. Explore practical examples and unlock the benefits of Sequence Diagrams for your software development and business analysis workflows.'
tags:
- Domain-Driven Design
- Workflow Modeling
- Requirement Validation
- Stakeholder Collaboration
---

New Blog: 'Unlocking the Power of Sequence Diagrams in Domain-Driven Design'

---

blog/2024/2024-07-23-optimizing-llm-agents-production-architectural-guide.md

---
title: 'Mastering LLM Agents: A Revolutionary Architectural Blueprint for Production-Ready AI Systems'
description: 'Explore the path to production for LLM agents with this comprehensive architectural guide. Learn about the ReWOO approach, RAG integration, and microservice implementation for efficient AI deployment. Discover best practices and future trends in LLM agent architecture.'
tags:
- LLM agents
- Artificial intelligence
- ReWOO approach
- Retrieval-Augmented Generation (RAG)
- Microservice architecture
- Production deployment
- AI best practices
- Future AI trends
- Explainable AI
---

New Blog: 'Mastering LLM Agents: A Revolutionary Architectural Blueprint for Production-Ready AI Systems'

---

blog/2024/2024-08-02.md
blog/2024/2024-08-03.md
blog/2024/2024-08-04.md
random_content.py

- Add 3 more posts generated by AI

feat: 3 more posts

---

blog/2024/2024-08-02.md
blog/2024/2024-08-03.md
blog/2024/2024-08-04.md
blog/2024/2024-08-12.md
blog/2024/2024-08-14.md
blog/2024/2024-08-20.md
random_content.py

- 3 more blog articles
- add truncate tags to few old ones

New Blog Posts and Some Fixes

---

docusaurus.config.ts
package.json
pnpm-lock.yaml

feat(search): integrate Algolia search functionality
